#!/bin/bash
cache_file="$HOME/.yc.tmp"
set -o pipefail

# pipe-viewer -sc tabletennisdaily, select the channel and :i=1
declare -A dict
dict['ping']='UC_1fAvMwuupRyQE5Fd2lZ2w UCqHc12tVGhzBtlMUq7MR7wA UCRnDl9NtKQDZVLn06Bwskrg UC9ckyA_A3MfXUa0ttxMoIZw UC_368FANcHhkhZ7oVqkW86A UCxccMOwsnVQEqmOU94MZi7g UC3_PnwGGlbEZjkD4YRDFn1g' # ,,,,,ittf,tabletennisdaily, adam bobrow , monqui pong
dict['jdr']='UCbM4Z7OzdBTip4fvMHvwG6A UCeMT9tun1lMbHOF7jsFNnZQ UCu47iib9xKIqcIaA_5ViWOw UC3nksGRcsiBJfjmx9ImBC1A UCsYsBPwucinBZUBUAbAyURg'
dict['info']='UCAcAnMF0OrCtUep3Y4M-ZPw UCUo1RqYV8tGjV38sQ8S5p9A UCynFUJ4zUVuh3GX7bABTjGQ UCQgWpmt02UtJkyO32HGUASQ'

request_channel() {
	pipe-viewer --no-use-colors --no-interactive --custom-layout="*AGE_SHORT* || *AUTHOR* || *TITLE* || *TIME* || *URL* || *CHANNELID* || *ID*" -uv=$1 -us=$1 >$2
	#if [ $? -eq 0 ]; then
	cat $2 >>$3
	#fi

}

generate_cache() {
	>$cache_file
	filename=$(mktemp)
	tmpfilename=$(mktemp)
	loading="Loading"
	curl -XPOST localhost:6266 -d "change-prompt[$(echo "Loading.>")]"
	for key in "${!dict[@]}"; do
		for channel_id in ${dict[$key]}; do
			request_channel $channel_id "$tmpfilename.$channel_id" $filename &
		done
		load="$load."
		curl -XPOST localhost:6266 -d "change-prompt[$(echo "Loading${load}>")]"
		wait
	done
	cat $filename | sed '/^$/d' | awk -F\| '{if($1!~/^[[:space:]]+/ && $1!~/^[[:digit:]]y+/ && $1!~/^[56789]m+/ && $1!~/^1[01]m+/){print $0}}' | sed -e 's/^1w/7d/g' -e 's/^2w/14d/g' -e 's/^3w/21d/g' -e 's/^4w/28d/g' -e 's/^1m/30d/g' -e 's/^2m/60d/g' -e 's/^3m/90d/g' -e 's/^4m/120d/g' | sort -n | uniq >>$cache_file
	rm -f $filename $tmpfilename
	LC_ALL=C sed -i -e 's/è/e/g' -e 's/ê/e/g' -e 's/é/e/g' -e 's/ô/o/g' -e 's/ç/c/g' $cache_file
	LC_ALL=C sed -i 's/[^[:blank:][:print:]]//g' $cache_file
	cat $cache_file
	curl -XPOST localhost:6266 -d "change-prompt[$(date) >]"
}

debug() {
	for key in "${!dict[@]}"; do
		for channel_id in ${dict[$key]}; do
			chaine=$(pipe-viewer --no-use-colors --no-interactive --custom-layout="*AUTHOR*" -uv=$channel_id -us=$channel_id | tail -n 1)
			if [ $? -eq 0 ]; then
				echo "$chaine $channel_id OK"
			else
				echo "$chaine $channel_id KO"
			fi
		done
	done
}

if [ "$1" == "-c" ]; then
	generate_cache
elif [ "$1" == "-d" ]; then
	debug
else
	if [ ! -f "$cache_file" ]; then
		generate_cache
	fi
	cat $cache_file | fzf -e --no-sort --delimiter='\|\|' --prompt "$(date --date="@$(stat -c %Z $HOME/.yc.tmp)") >" --bind "ctrl-r:reload(yc -c),enter:execute(pipe-viewer --no-video-info -3 -f --no-interactive -id {-1}),ctrl-y:execute[youtube-viewer -f --author={-2} {3} ]" --info=hidden --listen 6266
fi
